kafka:
  bootstrap-servers: localhost:9092
  input-topic: binance-exchange-input
  output-topic: binance-exchange-btc
  schema-registry: http://localhost:8081
  application-id: student-streams

playground:
  stream-type: exchange