kafka:
  bootstrap-servers: localhost:9092
  group-id: kafka-string-consumer-group
  topic: exchange-groupby-ticker-count
  schema-registry: http://localhost:8081

playground:
  consumer-type: exchange-count