kafka:
  bootstrap-servers: localhost:9092
  group-id: kafka-string-consumer-group
  string-topic-name: string-topic
  student-avro-topic-name: student-avro-topic
  schema-registry: http://localhost:8081

playground:
  consumer-type: string