kafka:
  bootstrap-servers: localhost:9092
  topic: binance-exchange-input
  schema-registry: http://localhost:8081

playground:
  producer-type: exchange

binance:
  exchange:
    tickers: BTCUSDT, ETHUSDT, XRPUSDT